In [1]:
import numpy as np
Day_number=np.arange(1,11)
step_walked=[4009,3000,2000,1000,5000,6001,7001,6000,6005,1000]
arr=np.array([Day_number,step_walked])
arr=arr.T
arr

array([[   1, 4009],
       [   2, 3000],
       [   3, 2000],
       [   4, 1000],
       [   5, 5000],
       [   6, 6001],
       [   7, 7001],
       [   8, 6000],
       [   9, 6005],
       [  10, 1000]])

In [2]:
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[   1, 6009],
       [   2, 5000],
       [   3, 4000],
       [   4, 3000],
       [   5, 7000],
       [   6, 8001],
       [   7, 9001],
       [   8, 8000],
       [   9, 8005],
       [  10, 3000]])

In [3]:
matched=arr[:,1]>6000
matched
new_arr=arr[matched]
new_arr

array([[   1, 6009],
       [   5, 7000],
       [   6, 8001],
       [   7, 9001],
       [   8, 8000],
       [   9, 8005]])